### ISSUE TITLE
Buttons not centered

### ISSUE THREAD

**Issue by nathancarter209** [nathancarter209/Portfolio#3]
Hi folks,
As you could see in the SS below that the button isn't centered. Need a fix for it. 

Thanks.
<img width="1274" alt="Screen Shot 2022-11-11 at 1 31 40 PM" src="https://user-images.githubusercontent.com/84240782/201294487-1088495d-ee3f-4548-9d72-bb6d329ecde7.png">

**Comment by maithani74** [comment]
Hi nathancarter209
I m willing to help your.
but first can your tell me which button you want to be centered 
which button you need to centered

**Comment by nathancarter209** [comment]
> Hi nathancarter209
> I m willing to help your.
> but first can your tell me which button you want to be centred
> which button you need to centered

sorry for the late response I wanted GitHub, SoundCloud and twitter button to be centred
